#!/bin/bash

# Phase 3 Order Management - Manual Test Guide

echo "=================================================="
echo "🚀 PHASE 3 ORDER MANAGEMENT - TEST GUIDE"
echo "=================================================="
echo ""

echo "✅ Files Created:"
echo "  1. app/orders/sales/page.tsx (476 lines)"
echo "  2. app/orders/[id]/page.tsx (393 lines)"
echo "  3. app/orders/sales/[id]/page.tsx (481 lines)"
echo ""

echo "📋 MANUAL TESTING CHECKLIST"
echo "=================================================="
echo ""

echo "Step 1: Start Development Server"
echo "  Run: npm run dev"
echo "  Visit: http://localhost:3000"
echo ""

echo "Step 2: Test Company Sales Dashboard"
echo "  URL: /orders/sales"
echo "  Tests:"
echo "    [ ] Revenue metrics display (5 cards)"
echo "    [ ] Orders table loads"
echo "    [ ] Search functionality works"
echo "    [ ] Status filter dropdown works"
echo "    [ ] Quick action buttons appear"
echo "    [ ] 'Start Work' button (paid orders)"
echo "    [ ] 'Mark Delivered' button (in_progress orders)"
echo "    [ ] 'Complete' button (delivered orders)"
echo "    [ ] Click 'View Details' navigates to detail page"
echo ""

echo "Step 3: Test Company Order Detail"
echo "  URL: /orders/sales/[order-id]"
echo "  Tests:"
echo "    [ ] Order status displays correctly"
echo "    [ ] Status action buttons appear"
echo "    [ ] Timeline shows all milestones"
echo "    [ ] Product information displays"
echo "    [ ] Internal notes can be typed"
echo "    [ ] 'Save Notes' button works"
echo "    [ ] Customer info card displays"
echo "    [ ] Earnings breakdown shows"
echo "    [ ] Contact customer button works"
echo "    [ ] Back button navigates to /orders/sales"
echo ""

echo "Step 4: Test Customer Order Detail"
echo "  URL: /orders/[order-id]"
echo "  Tests:"
echo "    [ ] Order timeline displays"
echo "    [ ] Completed stages show checkmarks"
echo "    [ ] Pending stages show clocks"
echo "    [ ] Product information displays"
echo "    [ ] Payment breakdown shows"
echo "    [ ] Seller card displays"
echo "    [ ] Contact seller button works"
echo "    [ ] Back button navigates to /orders"
echo ""

echo "Step 5: Test Database Queries"
echo "  Open Supabase Studio: https://app.supabase.com"
echo "  Run queries:"
echo "    [ ] SELECT * FROM product_orders WHERE company_id = 'your-company-id';"
echo "    [ ] SELECT * FROM product_orders WHERE buyer_id = 'your-user-id';"
echo "    [ ] Update status and check timestamps update"
echo ""

echo "Step 6: Test Status Workflow"
echo "  Create a test order through checkout"
echo "  Tests:"
echo "    [ ] New order appears with 'pending_payment' status"
echo "    [ ] After payment, status changes to 'paid'"
echo "    [ ] Company can click 'Start Work' → 'in_progress'"
echo "    [ ] Company can click 'Mark Delivered' → 'delivered'"
echo "    [ ] Company can click 'Complete' → 'completed'"
echo "    [ ] Timeline updates after each status change"
echo ""

echo "=================================================="
echo "🔍 DEBUGGING TIPS"
echo "=================================================="
echo ""
echo "If orders don't load:"
echo "  1. Check browser console for errors"
echo "  2. Verify Supabase credentials in .env.local"
echo "  3. Check user is logged in and has company profile"
echo "  4. Verify product_orders table has data"
echo ""
echo "If status updates fail:"
echo "  1. Check Supabase RLS policies allow updates"
echo "  2. Verify company_id matches logged-in user's company"
echo "  3. Check timestamps are being set correctly"
echo ""
echo "If revenue metrics are wrong:"
echo "  1. Check platform_fee is calculated (10% of total)"
echo "  2. Verify cancelled/refunded orders are excluded"
echo "  3. Check date filtering for monthly revenue"
echo ""

echo "=================================================="
echo "🎯 NEXT STEPS AFTER TESTING"
echo "=================================================="
echo ""
echo "1. Create Status Update API"
echo "   File: app/api/orders/[id]/update-status/route.ts"
echo "   Purpose: Centralize status updates with validation"
echo ""
echo "2. Implement Stripe Webhooks"
echo "   File: app/api/stripe/webhooks/route.ts"
echo "   Purpose: Auto-update orders when payments succeed"
echo ""
echo "3. Add Email Notifications"
echo "   Library: Resend (npm install resend)"
echo "   Purpose: Notify users of order updates"
echo ""
echo "4. Deploy to Production"
echo "   Platform: Vercel"
echo "   Steps: Configure env vars, webhooks, domain"
echo ""

echo "=================================================="
echo "📊 QUICK DATABASE CHECK"
echo "=================================================="
echo ""

# Check if Supabase CLI is installed
if command -v supabase &> /dev/null; then
    echo "✅ Supabase CLI is installed"
    
    # Check if project is linked
    if [ -f ".git/config" ]; then
        echo "✅ Git repository found"
    fi
    
    # Try to get status
    echo ""
    echo "Running: supabase status"
    supabase status || echo "⚠️  Supabase not linked. Run: supabase link"
else
    echo "⚠️  Supabase CLI not installed"
    echo "Install with: brew install supabase/tap/supabase"
fi

echo ""
echo "=================================================="
echo "✨ Happy Testing! ✨"
echo "=================================================="
